### ISSUE TITLE
[Proposal] Cache modules by name & semver

### ISSUE THREAD

**Issue by maurizzzio** [maxogden/browser-module-sandbox#10]
`preferredVersions` is only used with non-cached modules, if `bundle` is called multiple times, each time with a different version for a package the cache will always return the first bundle created regardless of the version

e.g.

Let say that there's a package `foo@1.0.0`

```javascript
var sandbox = new Sandbox();
sandbox.bundle("require('foo')");

// sandbox will cache the package foo, cache.foo = bundle + meta for foo@1.0.0
```

Let's say that the package foo was updated to `foo@2.0.0`, to avoid getting the one in the cache `preferredVersions` should act as an 'override'

```
var preferredVersions = {
  foo: '2.0.0'
};
sandbox.bundle("require('foo')", preferredVersions);

// sandbox will return foo@1.0.0 since the cache works by module name only
```

**Comment by maxogden** [comment]
oh yea good point. +1
