### ISSUE TITLE
Change the way of inserting script?

### ISSUE THREAD

**Issue by voronianski** [maxogden/browser-module-sandbox#13]
@maxogden is there any specific reason why script is inserted with inlining into `src` param - https://github.com/maxogden/browser-module-sandbox/blob/master/index.js#L139

It's executed really slow comparing to concatinating code inside script tag like this, e.g. `'<script>'+script+'</script>`.

**Comment by maxogden** [comment]
history is here: https://github.com/maxogden/browser-module-sandbox/commit/542347f5689130721f935fad684adb26a1631d58, @hughsk do you think this is still necessary?

**Comment by hughsk** [comment]
@maxogden @voronianski the problem with `'<script>'+script+'</script>'` is that if the script contains `</script>` anywhere in the source the script will get closed early — this would break with packages using esprima (https://github.com/maxogden/requirebin/issues/27).

Slightly faster than `encodeURIComponent` was to encode the source using base64, but then that would only support ASCII characters which would break stuff like d3. Looking at it now, one thing worth trying would be to construct a [`Blob`](https://developer.mozilla.org/en/docs/Web/API/Blob) URI and load that up. It might not be shared across frames though, so may need some further prodding to get working.

A quick fix for speedups would be to check if the source contains `</script>` anywhere and only use the fallback method in that case.

p.s. I'm on a GitHub holiday for February :tada: So won't be able to follow up for now :)

**Comment by maxogden** [comment]
ah that makes sense, thanks @hughsk. enjoy your holiday. if i see you on
github this month ill call the github police

**Comment by hughsk** [comment]
Haha, thanks @maxogden! I'm having a hard time staying disciplined with it :P

**Comment by voronianski** [comment]
@hughsk @maxogden I tried with blob however it doesn't work:

```js
var blob = new Blob(['setTimeout(function(){\n;' + script + '\n;}, 0)'], {type: 'text/javascript'})
var url = URL.createObjectURL(blob);
var body = self.iframeBody + '<script type="text/javascript" charset="UTF-8" src="'+url+'"></script>'
// ...
```

Chrome returns error `Not allowed to load local resource: blob:http%3A//localhost%3A9292/7515baa1-2e96-476a-82d2-4b9f4382307d`

**Comment by voronianski** [comment]
I've create PR with check for `</script>` inside code string, if everybody is fine with it I'll merge it.
