### ISSUE TITLE
require('browser-module-sandbox') sets window.XMLHttpRequest to undefined

### ISSUE THREAD

**Issue by CharlesHolbrow** [maxogden/browser-module-sandbox#2]
I ran into an issue while running RequireBin locally.

RequireBin uses XMLHttpRequest to retrieve an access token from Github. Currently it throws a "Can't call undefined" error when attempting to retrieve a OAuth access-token. 

Note that the access token is stored in a cookie, so you would have to clear cookies to duplicate the error. 

Here's my temporary (hacky) fix illustrating the problem:
https://github.com/CharlesHolbrow/requirebin/blob/6e7654c289ff4dd9d7097e5289327e46b3222d16/index.js#L5-L7

**Comment by voronianski** [comment]
@CharlesHolbrow I can't reproduce that..
